# Week 1: An introduction to remote sensing

## Summary

Remote sensing is a form or a process of data collection over the earth body, which include but not limited to:

1.  Biosphere (living organisms/ forms)
2.  Hydrosphere (terrestrial, oceanic, supra- or subglacial water body)
3.  Cryosphere (ice sheets, glaciers, sea ice, ice bergs)
4.  Atmosphere (clouds, aerosols)
5.  Lithosphere (soil)

Remote sensing is usually achieved using remote sensors that are on board with the satellites or aircrafts. It is also a form of cloud computing data source that requires certain computational technologies to complete remote sensing. The most well-known service provider is the National Aeronautics and Space Administration (NASA), providing numerous open data source for easy public assess [@earthinformationcentre2024].

### Active VS passive sensors

Remote sensing mainly adopt two different types of sensors on board each of the satellite or aircrafts -- active and/ or passive. Active sensor actively emit energy, electromagnetic waves, to the ground or targeted surfaces. It then detects any changes in the returning signal (e.g., wavelength) and calculate the returning time for the approximate distance between the two.

![Graph illustration showing the operations of active sensor [@gisgeography2024].](images/Active-Satellite-Double-Bounce.png){fig-align="center"}

Passive sensor does not emit energy, it detects the reflected energy (also electromagnetic waves) from the illuminating source -- the Sun.

![Graph illustration showing the operation of passive sensor [@gisgeography2024].](images/passive-satellite.png)

#### Electromagnetic waves/ signatures

Electromagnetic waves are the ways of energy being transported/ travelled around, like ocean waves, but electromagnetic waves do not require any medium for movement (they can even transported through a vacuumed space). Electromagnetic waves change according to the objects that they have encountered, which creates unique electromagnetic signatures -- wavelengths for measurements (this also forms the electromagnetic spectrum). Electromagnetic waves are measured according to their wavelength -- the distance between the crests (highest point of the cycle), while units of measurement vary from nanometers to meters. As different materials reflect different values of electromagnetic waves, sensors then measure the changes/ types of electromagnetic wave to determine the properties of the remotely sensed material.

![Reflected wavelengths of physical material of the Earth within the visible light spectrum [@earthdataa].](images/spectralfingerprints.jpg)

### Resolutions

Resolutions tell the primary information about the satellite imagery, they vary across different products and service providers. There are 4 types of resolutions:

**1. Spatial:** It measures the size of a single grid/ pixel in the unit of cm/m/km squared. The higher the spatial resolution, the more detail of the features can be revealed.

**2. Temporal:** It measures the revisiting time of the sensors (satellite) in the unit of day, week, month, year. The higher the temporal resolution, the more frequent the revisiting time.

**3. Spectral:** It reveals the number of bands a sensor can observe. The higher the spectral resolution, the higher number of bands can be detected (objects with more wavelengths can be detected as well).

**4. Radiometric:** It reveals the ability of a sensor to accurately perceive and store signal, it is told by the number of bit. The higher the radiometric resolution, the higher the information/ colours it can perceive and store.

## Applications

With the rapid development of technologies and the availability of open-source data, remote sensing has been widely applied across sectors: environmental protections/ conversations, disaster risks reductions, humanitarian crisis etc. The most notable break through in scientific research using remote sensing is the examination of sea-level rise in both global and local level. A new era in sea-level monitoring is facilitated by remote sensing -- the satellite altimetry era since 1992/1993 [@theearthobservatory2022].

Prior to the availability of satellite altimetry measurements of sea-level change, the only way to monitor sea-level change was using in-situ tide gauge along the coast. The limitations of using tide gauge is the spatial coverage of sea-level monitoring, it's limited to coastal regions not open sea, and the uneven global distributions of tide gauge stations [@beenstock2015].

![Map showing the distributions of in-situ tide gauges (black dots) and the coverage of satellite altimetry measurements (orange grids) by Jason-3 [@earthobservatory2020].](images/tides_jsn_psmsl_2020.png)

### High-precision satellite altimetry era

Since 1992/1993 when JASON/POSEIDON satellite series made available, it gave rise to a more comprehensive overview of sea-level change. @doi:10.1098/rspa.2022.0049 applied satellite altimetry measurement to examine trends of global and local sea-level rise. It provides a more comprehensive spatial coverage of sea-level changes, allows the monitoring of absolute sea-level change in both coastal and open sea regions. The merits of @doi:10.1098/rspa.2022.0049 work in 2022 are they also conducted model ensemble modelling, compiling several satellite altimeter data sets together to obtain mean observations to minimise biases from certain data sets. The second merit of @doi:10.1098/rspa.2022.0049 is the ability to utilise altimetry record to demonstrate variations in regional sea-level change and the importance of the corrections of glacial-isostatic adjustment (GIA) and vertical land motion (VLM).

It is important to correct all possible noises e.g., local VLM brought by groundwater extractions and account for uncertainties as highlighted by @prandi2021. Global sea-level budget is a continuous evolving concept with numerous uncertainties brought by different components e.g., local rates of VLM, extent of GIA, ENSO cycle etc [@https://doi.org/10.1002/2016GL070750]. Therefore, it is important to consider errors and limitations while applying remote sensing in monitoring global/ local sea-level changes. While @doi:10.1098/rspa.2022.0049 paper is able to perform the awareness of the uncertainties listed above, to enhance the validity and precision of their analysis and remote sensing applications.

![Observed regional absolute sea-level change using satellite altimetry data with corrections [@doi:10.1098/rspa.2022.0049].](images/rspa20220049f09.jpg)

## Reflections

I quite enjoyed the lecture as the content was quite fascinating. As a geographer (before I came to the CASA), I usually used remote sensing data such as satellite imagery or altimeter measurement data sets, to reconstruct past observations or project future changes but not know much about how remote sensing works. Learning the function and theory of how remote sensing work during the lecture provided me with insight on how to choose a more suitable remote sensing data sets for my (future) research based on the characteristics of the satellites and resolutions of the data sets.

After the lecture and practical sessions, I am more confident in explaining the methodology involved in remote sensing, such as how they actually work. Although it takes some time for me to digest the content, I think this lecture has laid down a foundation for understanding the application of remote sensing. I was amazed by how remote sensing can benefit from the advanced technological development in this modern world, from in-situ monitoring stations/ field studies to remotely sensing the environment just by clicking a few buttons and downloading the required data. Remote sensing has definitely made our lives easier in terms of monitoring environmental change, especially under the context of rapid global warming as we can see that remote sensing techniques are now being widely used in disaster risk reduction in different UN reports e.g., AR5 (Assessment Report 5).
