# Week 4: Policy -- The Bihar Kosi Recovery Project

## Summary

Kosi River is a trans-boundary river -- upper steam flowing along Nepal all the way down to lower course in the Bihar region in India [@nhess-13-795-2013]. It subjected to repeated flooding, especially during the Summer Monsoon season from June to September. The most notable and disastrous flood was in 2008 -- as known as the 2008 Kosi Flooding. The 2008 Kosi Flooding was originated from the breach of upstream embankment, channel discharge then rapidly displaced to downstream of Kosi, in the North Bihar regions [@dixit2009]. 6 districts in the North Bihar was inundated; 5.5 million people became homeless; more than 2500 km2 of cultivated land was submerged; economic loss of US\$18.7 million was also reported [@kafle2017]. Since then, the Indian government started the **Bihar Kosi Flood Recovery Project** [@biharko2010] to revitalise the Northern Bihar and enhance its flood resilience capacity.

![LANDSAT image showing the abandoned paleochannel that are marked by their avulsion year and the flooded areas during the 2008 Kosi Flood (shaded in red). A continuous avulsion of Kosi to the west to its current location is observed since 1760 the earliest [@CHAKRABORTY2010143].](images/Kosi_avulsion.jpg){fig-align="center"}

It is important to note that Kosi River is a dynamic river as it has shifted westward for at least 113 m to the current location due to active tectonic movements [@CHAKRABORTY2010143]. Its dynamic nature created numerous abandoned channel that increases the risks of flooding to surrounding area, by providing more flood water outlets through the abandoned paleochannels. Therefore, it is equally important to understand its physical settings while progressing on socio-economic reconstructions.

The project objectives of the "Environment and Social Management Framework" [@biharko2010a] are listed as follow:

1.  Reconstruction of houses that are earthquake and flood resistant
2.  Enhancing connectivity by building and repairing roads and bridges
3.  Strengthening flood management capacity in Kosi Basin
4.  Building social and financial capital by expanding livelihoods opportunities

## Application

This project did not outline the use of remote sensing techniques in post-disaster reconstruction and flood management; therefore, I am going to suggest the application of MODIS (Moderate Resolution Imaging Spectroradiometer) to enhance the precision and efficiency for post-disaster reconstructions and disaster risk reductions [@earthdata]. This suggestion is inspired by @ARVIND2016575, where they proposed the use of satellite images from different months to identify and predict the flood extents for the next possible flood occurrence. They successfully applied to one of the flood events in 2009 in the southern part of India (across various local regions), to identify the extent of flooded and non-flooded areas through remote sensing. MODIS can monitor changes in the biosphere -- land cover; atmosphere -- cloud cover (potential rainfall); hydrosphere -- water level/ extent of water body; cryosphere -- extent of snow cover [@modis2018]. In addition to that, remote sensing is beneficial for monitoring areas that are still under the impact of flood inundation for post-disaster risk reduction. Therefore, MODIS would be undoubtedly beneficial for the recovery project and link with the global agendas and goals:

1.  The Sendai Framework for Disaster Risk Reduction [@undrr]
2.  SDGs 3 (Good Health and Well-being), 6 (Clean Water and Sanitation), 11 (Sustainable Cities and Communities) [@theunitednations]

And most importantly the local policy...:

1.  Identify vulnerable houses that are exposed to flood hazards (close to riverbank)
2.  Identify collapsed infrastructure(s)
3.  Monitor water level especially in the upper course in Nepal (to avoid rapid displacement of flood water due to a sudden increase of channel discharge)
4.  Identify non-flooded cultivated land/ newly built fertile soil (by flood sediments) for agricultural activities

![Satellite image (top) and processed image (bottom) from MODIS showing the extent of flooding half month later flood occurrence in mid August [@ARVIND2016575].](images/Kosi_TMO_DFO_2008246.jpg){fig-align="center"}

However, some also suggested the use of Sentinel-2 data as an alternative for flood detection and management due to its high resolution and the availability of Synthetic Aperture Radar (SAR) sensors on board [@w11122499a]. Although Sentinel-2 provides a higher resolution of 10 m, its revisit time required is longer than MODIS. The temporal resolution of MODIS is higher than Sentinel-2 at 2 to 3 days while having a spatial resolution of 250 m to 1000 m [@earthdata]. In Bihar region, where it suffers from heavy summer monsoon rainfall at a temporal scale at daily and weekly, it is necessary to monitor water levels and flood extent at a smaller temporal interval [@AHAMED2017104]. The smaller the temporal resolution, the better the flood detection and monitoring.

## Reflection

Remote sensing is an extremely useful technique in monitoring environmental changes (as I said before), the question I would like to raise are: why some countries do not incorporate remote sensing into their policy scopes for monitoring changes? what makes them refuse to deploy remote sensing? Well, I mean remote sensing is an excellent tool for spatial management but it is kind of costly, and it might not be affordable for every country/ local authoritys. To apply remote sensing in policy development and monitoring, first, we --- the professional (data analyst) require funding for that (including salary, data procurement, data processing, and product output fees); secondly, we also need time for data processing (that could be a long and tiring time for both professionals and local authorities). There are many considerations and negotiations between the government, professionals (could be individual or academia), and local citizens to go through, especially about the costs of deploying remote sensing and the use of remote sensing products for regional development e.g.., what policy decision to be made regarding the product. IT IS A COMPLICATED MOVE.

For my case study in Bihar (Kosi River), India, I think is it absolutely reasonable to deploy remote sensing for the recovery project. The reasons are 1). we never know when the next breach will happen 2). we have to understand the exposure of local communities to flood risks 3). we have to identify areas for immediate restoration. It is important for us to closely and continuously monitor flood risks by remotely sensing changes in the physical environment for pre- and post-disaster risk reductions. There is a wide range of products available, it is important to apply the products to our study context accordingly I would prefer the use of MODIS over Sentinel-2 in the Bihar regions. It also once demonstrates that the types of products that we are going to use are simply based on the study context.
