# Week 8: SAR

## Summary

### Background

Synthetic Aperture Radar -- SAR is an active sensor whose bands are able to pass through clouds and reach the ground/ target surface, disregarding the weather condition e.g., the percentage of cloud covers during the sensing date. It has a total of 8 bands that are tailored for different applications, its wavelength also has its own frequencies so that it would not be disturbed by other sensors. It is important to note that *calm* water usually appears dark in the SAR image as it reflects the energy pulses away from the sensor (pulses cannot be reflected back to the sensor).

![Wavelength of different bands in SAR [@earthdatab].](images/SARwavelength.png)

### Polarisation

SAR detects both vertical (V) and horizontal (H) transmission as different surfaces respond differently to polarisations:

1.  Rough surface scattering: VV (most sensitive)

2.  Double bounce (pulses bounce twice before reflecting to the sensors e.g., buildings): HH (most sensitive)

3.  Volume scattering (for objects with complex volume/ structures that waves can bounce and reflect within them): VH or HV

Here it is also important to note *rough* water surface e.g., wavy during windy time or tsunami can reflect pules back through VV transmission.

![Graph showing different polarisation from different objects [@earthdatab].](images/SARPolarization.jpg)

### SAR techniques

1.  InSAR: Interferometric synthetic aperture radar

    Combine multiple SAR image over the same location to records topography, ideally for creating DEMs

2.  DInSAR: Differential Interferometric synthetic aperture radar

    Detect differences and changes between two images at different times, ideally for looking at vertical land movement (VLM) e.g., land uplift or subsidence

## Applications

As mentioned above, SAR images are useful in detecting land motion (uplift or subsidence), therefore, I have chosen a case study of detecting vertical land motion -- land deformation along the Houston-Galveston region in Texas, the USA [@QU2015290]. The Houston-Galveston is vulnerable to land subsidence due to its natural lithology -- compaction of fine-grained sediments e.g., clay and silt AND human influence -- groundwater extraction that led to compaction of soil [@usgs]. The authors compare SAR images from ERS-1/2 ENVISAT SARs and ALOS POLSAR across different timescales, to perform multi-temporal -- PS-InSAR analysis [@QU2015290]. For spatial analysis, an interferogram and choropleth map are produced to identify regions that are subjected to intense vertical land movement -- land subsidence. This provides an insight to the audience of areas that are prone to land subsidence, to address the urgency in mitigating local land subsidence e.g., through policy regulations or hard engineering methods [@piahs-382-809-2020].

![Spatial deformation map in Huston-Galveston using InSAR techniques. a). ERS b). Envisat c). ALOS [@QU2015290].](images/Huston_spatial.jpg)

For temporal analysis, the authors demonstrate the changes of land elevation across (more than) 32 years. This provides a comprehensive overview of changes in land subsidence rates across the trend, enabling the audience to identify the significance of land subsidence to the local region across time.

![Land subsidence across time series for at least 32 years (temporal analysis) in Huston-Galveston using InSAR techniques [@QU2015290].](images/huston_temporal.jpg)

The merits of @QU2015290 papers are they also conducted analysis on the possible contributing factors of land subsidence e.g., hydrologic settings (changes in channel characteristics in Huston-Galveston), fault systems, and lithological settings (soil profile). This allows the analysis of the causal relationship between the physical settings and land subsidence. However, the limitation of this paper falls on the omission of human influence on land subsidence. The high-resolution-SAR images would undoubtedly be beneficial for identifying the changes in the spatial distribution of water bodies e.g., enhanced coastal flooding due to land subsidence [@navarro-hernández2023]. The utilisation of SAR imagery in this paper leaves room for improvements.  

Apart from the paper itself, there are some limitations of using InSAR to detect land motion. As InSAR is detecting changes between two images within the same pixels, it is important that there is no horizontal displacement of the plate (should not be greater than 6 cm that out of the radar wavelength of Sentinel-1) [@eage:/content/papers/10.3997/2214-4609.20215521143]. The recorded data should also be calibrated with the GNSS data to ensure the point is referenced correctly.

## Reflections

SAR image is just another level...! It does not only provide a high resolution but is also not limited by weather conditions (they can pass through clouds)! It is extremely useful for remotely sensing places with clouds covered all the time e.g., the tropical areas (Indonesia, Singapore, Brazil... etc.) where there are rapid and frequent cloud formation. I was, again, amazed by how far the technology could go in remote sensing! It facilitates the monitoring of environmental changes in tropical countries, where natural disasters and human influence e.g., deforestation are rapidly taking place. The availability of SAR would definitely be beneficial to those countries (or at least research around those regions). Another reason for SAR being on the next level is that SAR allows the generation of interferograms, therefore, monitoring land displacement. It is a breakthrough in the monitoring of vertical land movement (VLM) brought by both human and physical factors, just by comparing two satellite imagery across different times. Satellite missions with SAR on board e.g., Sentinel-1/ ALOS have made many positive contributions in monitoring the displacement of land. That's why I am saying SAR is on the next level!
