# Week 3: Corrections and enhancement

## Summary

Remote sensing often requires corrections or sometimes requires enhancement to overcome the flaws of the original image introduced by sensor itself (e.g., angle of viewing)/ landscape (e.g., hilly surface)/ atmosphere (e.g., atmospheric scattering of radiation) etc. Enhancement of imagery also allows better interpretation for spatial analysis e.g., identifying features. 

### Key Terms: Corrections



1.  **Geometric corrections** for image distortions introduced by physical factors e.g., sensor/ landscape itself

    -   Ground Control Points (GCPs) from local map or handheld devices needed to match the known points (of the image) to a location-referenced dataset.

    -   Geometric transformation algorithms to obtain RMSE (root-mean-squared-error), the lower the better ~0.5.

    -   More GCPs are required in order to lower the RMSE.

    -   Resample the raster layer.

2.  **Atmospheric corrections** for image distortions introduced by atmosphere e.g., atmospheric scattering and topographic attenuation

    -   Necessary for measuring biophysical parameters e.g., NDVI (Normalised Difference Vegetation Index).

    -   Relative VS Absolute.

    -   Relative: the use of Dark Object Subtraction (DOS) or Pseudo-invariant Features (PIFs) to normalise relative to different bands within an image OR relative to different dates.

    -   Absolute: requires empirical data e.g., atmospheric model and local atmospheric visibility to scale up surface reflectance.

3.  **Orthorectification** correction for image distortions introduced by the view angle of the sensor • Requires geometry and DEMs (elevation model).

    -   Consider the effect of solar azimuth and solar zenith.

    -   Solar azimuth:

    -   Solar zenith:

4.  **Radiometric Calibration** for transforming image brightness from Digital Number (DN) to spectral radiance

    -   Sensors only able to capture image brightness and stored as DN.

    -   Calibrated in a lab before launching the sensor.

### Key terms: miscellaneous

1.  **Digital Number (DN):** in a form of binary integer (bits) that requires transformation, represents the intensities (brightness) of a pixel.

2.	**Radiance/ Top of Atmosphere (TOA) radiance:** the amount of light that a sensor receives through reflectance from an object, with a unit of watt.


3.	**(Surface) Reflectance:** property of a material being observed, dependent on light source (requires illuminating source for reflection to take place).
    **TOA reflectance:** converted from TOA radiance.
    
4.	**Band Ratioing:** (for DN values in different bands), to compare DN values in different bands to look at the differences e.g., NDVI (Normalised Difference Vegetation Index, to be discussed in the applications part).

5.	**Principal Component Analysis (PCA):** the transformation of original data to a new one for dimensionality reduction, from multi-spectral data to uncorrelated/ smaller dataset.

6.	**Texture:** captures the spatial distribution of grey values.

7.	**Fusion:** combining data from different (multiple) sources into one. 


## Applications

## Reflections
